[plugin]
repository = "https://github.com/goaaats/Dalamud.RichPresence.git"
commit = "d335b9ca5452fd6fd3d8e5ec9ea27f00eab4fa49"
owners = [
    "goaaats",
    "test",
]
project_path = "Dalamud.RichPresence"
